application: ch5conf
version: 201208121413
runtime: python
api_version: 1

handlers:
# belows are static resources
- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css


- url: /javascripts
  static_dir: javascripts

- url: /images
  static_dir: images

- url: /bootstrap
  static_dir: bootstrap

# doesn't used now
- url: /admin/.*
  script: admin.py
  login: admin


# redirect to newest event page
- url: /
  script: main.py


# Aut 21st, 2012 conference

#- url: /.*
#  script: main.py
- url: /conference/2011/08/.*
  script: 201108/main.py

# Sept 8th, 2012 conference

- url: /conference/2012/09/.*
  script: 201209/main.py

